In [98]:
import numpy as np
import pandas as pd

In [99]:
df=pd.read_excel(r"C:\Users\Lenovo\Downloads\A213070490_15745_18_2019_data.xls")

In [100]:
df.head()

Feature-1  Feature-2  Feature-3  Feature-4 Class_Label
0        5.1        3.5        1.4        0.2     Class-1
1        4.9        3.0        1.4        0.2     Class-1
2        4.7        3.2        1.3        0.2     Class-1
3        4.6        3.1        1.5        0.2     Class-1
4        5.0        3.6        1.4        0.2     Class-1

In [101]:
df.shape[0]  # rows

150

In [102]:
df.shape[1]# columns

5

In [103]:
df['Class_Label'].nunique()     # no of unique class

3

In [104]:
df['Class_Label'].value_counts()           # no of elements belongs to each class

Class-2    50
Class-3    50
Class-1    50
Name: Class_Label, dtype: int64

In [105]:
df.head()

Feature-1  Feature-2  Feature-3  Feature-4 Class_Label
0        5.1        3.5        1.4        0.2     Class-1
1        4.9        3.0        1.4        0.2     Class-1
2        4.7        3.2        1.3        0.2     Class-1
3        4.6        3.1        1.5        0.2     Class-1
4        5.0        3.6        1.4        0.2     Class-1

In [106]:
# missing values
df.isnull().sum()

Feature-1       8
Feature-2      13
Feature-3       7
Feature-4       9
Class_Label     0
dtype: int64

In [107]:
df.tail()

Feature-1  Feature-2  Feature-3  Feature-4 Class_Label
145        6.7        3.0        5.2        2.3     Class-3
146        6.3        2.5        5.0        1.9     Class-3
147        6.5        3.0        5.2        2.0     Class-3
148        6.2        3.4        5.4        2.3     Class-3
149        5.9        3.0        5.1        1.8     Class-3

In [108]:
#      d=df.dropna()     to # drop missing values this is not good approch
print(d.shape)   # no of records after dropna

(121, 5)


In [109]:
# label encoder
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
le.fit(df['Class_Label'])


LabelEncoder()

In [110]:
list(le.classes_)

['Class-1', 'Class-2', 'Class-3']

In [111]:
df['Class_Label']=le.transform(df['Class_Label'])

In [112]:
df.head()

Feature-1  Feature-2  Feature-3  Feature-4  Class_Label
0        5.1        3.5        1.4        0.2            0
1        4.9        3.0        1.4        0.2            0
2        4.7        3.2        1.3        0.2            0
3        4.6        3.1        1.5        0.2            0
4        5.0        3.6        1.4        0.2            0

In [123]:
# imputer method for missing values
from sklearn.preprocessing import Imputer
imf=Imputer(missing_values=np.nan,strategy='mean',axis=0)
imp=imf.fit(df)
imputed_data=imp.transform(df.values)
imputed_data

array([[ 5.1       ,  3.5       ,  1.4       ,  0.2       ,  0.        ],
       [ 4.9       ,  3.        ,  1.4       ,  0.2       ,  0.        ],
       [ 4.7       ,  3.2       ,  1.3       ,  0.2       ,  0.        ],
       [ 4.6       ,  3.1       ,  1.5       ,  0.2       ,  0.        ],
       [ 5.        ,  3.6       ,  1.4       ,  0.2       ,  0.        ],
       [ 5.4       ,  3.9       ,  1.7       ,  0.4       ,  0.        ],
       [ 4.6       ,  3.4       ,  1.4       ,  0.3       ,  0.        ],
       [ 5.        ,  3.4       ,  1.5       ,  0.2       ,  0.        ],
       [ 4.4       ,  2.9       ,  1.4       ,  0.2       ,  0.        ],
       [ 4.9       ,  3.1       ,  1.5       ,  0.1       ,  0.        ],
       [ 5.4       ,  3.7       ,  1.5       ,  0.2       ,  0.        ],
       [ 4.8       ,  3.4       ,  1.6       ,  0.2       ,  0.        ],
       [ 4.8       ,  3.        ,  1.4       ,  0.1       ,  0.        ],
       [ 4.3       ,  3.        ,  1.1

In [124]:
  #df.fillna(df.mean(),inplace=True)
df.dtypes

Feature-1      float64
Feature-2      float64
Feature-3      float64
Feature-4      float64
Class_Label      int64
dtype: object

In [125]:
df.head()
x=imputed_data[:,:4]
y=imputed_data[:,4]

In [126]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(x_train.shape)
print(y_test.shape)








(105, 4)
(45,)


In [127]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_std=sc.fit_transform(x_train)
x_test_std=sc.fit_transform(x_test)


In [128]:
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()
x_train_nom=mn.fit_transform(x_train)
x_test_nom=mn.fit_transform(x_test)


In [129]:
# apply logistic regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train_std,y_train)
y_pred=lr.predict(x_test_std)

print('misclassified samples: %d'%(y_test!=y_pred).sum())

from sklearn.metrics import accuracy_score



print("accuracy:%f"%accuracy_score(y_test,y_pred))


misclassified samples: 4
accuracy:0.911111


In [130]:
# apply logistic regression with penaality
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=1,random_state=0,penalty='l2')
lr.fit(x_train_std,y_train)
y_pred=lr.predict(x_test_std)

print('misclassified samples: %d'%(y_test!=y_pred).sum())

from sklearn.metrics import accuracy_score



print("accuracy:%f"%accuracy_score(y_test,y_pred))


misclassified samples: 4
accuracy:0.911111


In [131]:
 # confusion matrix
from sklearn.metrics import confusion_matrix
cmat=confusion_matrix(y_pred,y_test)
print(cmat)

[[15  0  0]
 [ 1 12  1]
 [ 0  2 14]]


In [132]:
from sklearn.metrics import classification_report       # classfication reorts
print(classification_report(y_pred,y_test))

             precision    recall  f1-score   support

        0.0       0.94      1.00      0.97        15
        1.0       0.86      0.86      0.86        14
        2.0       0.93      0.88      0.90        16

avg / total       0.91      0.91      0.91        45

